### ISSUE TITLE
User is unable to change password

### ISSUE THREAD

**Issue by FJKhan** [asylum-connect/control-panel#52]
Reported by Jamie on June 16 2021

**Comment by Alfredo-Moreira** [comment]
Tested this and it is working properly.

Added Test User:
<img width="1159" alt="Screen Shot 2021-09-20 at 2 42 08 PM" src="https://user-images.githubusercontent.com/11844106/134073135-bf75fbc8-38d3-4e23-899a-678def2f9a91.png">

Changed Password:
<img width="1409" alt="Screen Shot 2021-09-20 at 2 41 52 PM" src="https://user-images.githubusercontent.com/11844106/134073529-35c9c465-4cc4-447e-8431-9276bed022ce.png">

Logged out, then attempted to log in with old password:
<img width="955" alt="Screen Shot 2021-09-20 at 2 42 12 PM" src="https://user-images.githubusercontent.com/11844106/134073615-af64d1c0-381e-47ea-a71b-3ebe57f1b6f1.png">

Tried new password and I got in:
<img width="1063" alt="Screen Shot 2021-09-20 at 2 42 20 PM" src="https://user-images.githubusercontent.com/11844106/134073679-a45316e5-4903-4b4c-98ec-14fc64f71a09.png">

**Comment by Alfredo-Moreira** [comment]
Closing this issue
